export const SET_SIGNUP_ERRORS = "SET_SIGNUP_ERRORS";
export const SET_SIGNUP_SUCCESS = "SET_SIGNUP_SUCCESS";
export const SET_LOGIN_ERRORS = "SET_LOGIN_ERRORS";
export const CLEAR_LOGIN_ERRORS = "CLEAR_LOGIN_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";